### ISSUE TITLE
does not identify a student account

### ISSUE THREAD

**Issue by LeonardoBTT** [agam778/MS-Office-Electron#13]
error received when trying to log in using a student account
message: this Microsoft account does not exist. Enter a different account or get a new one.

Error Code: 80041012
Correlation Id: 1c5bc1a5be1540d99f410aa342955309
Timestamp: 2022-03-29T15:40:13.615Z

![image](https://user-images.githubusercontent.com/25851672/160650743-ccc6c58f-283b-4965-94d1-8bfebfcfd78b.png)

Transcription: this Microsoft account does not exist. Enter a different account or get a new one.

**Comment by agam778** [comment]
Hi! Actually enterprise/student accounts don't work. It requires some extra things in the code. Microsoft's issue.
