### ISSUE TITLE
Re add Enterprise Version Option

### ISSUE THREAD

**Issue by jlokos** [agam778/MS-Office-Electron#15]
Hi, 

I have tried the latest release and it does not work with enterprise accounts as expected. However, I tried version 0.3.5 which was the latest version that supported it and I was able to successfully login and use it. Are you able to re add the feature as it is very helpful and I would prefer to be on the latest version. If not I can submit a Pull request

Thanks!

**Comment by agam778** [comment]
Hey! Sure, you can login to the enterprise account. But try creating and open any document.

**Comment by jlokos** [comment]
Creating a document works as long as "Open New Websites in New Windows" is selected, otherwise I don't receive any error just a blank window. I would have to check devtools to see exactly why that is. Additionally, opening any document whether using "Open New Websites in New Windows" or not works!

**Comment by jlokos** [comment]
Just checked the devtools and whenever I am using the option to open the website in the same window it appears upon creating a new document the XHR request get cancelled. Any ideas?

**Comment by agam778** [comment]
Closing this issue and moving this topic to the PR you opened (#16)
