### ISSUE TITLE
Auto hide menu bar 

### ISSUE THREAD

**Issue by AnisTaluqdar** [agam778/MS-Office-Electron#19]
In linux the menu bar is not hiding automatically instead of pressing alt. I said you before but you said it's electron problem.
(https://github.com/oitsjustjose/Overleaf-Desktop) but this app also electron based app it has not this problem. When I hide the menu bar from setting this app automatically hide the menu bar. But MS-Office can not hide that, still it is already select auto hide. I need to press alt or click the minimize window.

**Comment by AnisTaluqdar** [comment]
bro, can you create  https://colab.research.google.com/

Electron app?

**Comment by agam778** [comment]
Hi! Yes i can make an electron wrapper for that too, but actually I am kinda busy these days, you can check https://github.com/agam778/basic-electron-app and make your own ig.

Anyways this issue is solved? May I close it?
