### ISSUE TITLE
Will you do something about telemetry?

### ISSUE THREAD

**Issue by Vannywasnotavailable** [agam778/MS-Office-Electron#5]
Dude, this is incredible, but the only thing holding me back from loving it is that am not sure if you block the trackers.

**Comment by agam778** [comment]
Do you mean trackers on the microsoft office website?

**Comment by Vannywasnotavailable** [comment]
Yep, all the tracking stuff. It makes it kinda slow, and I think doing something to counter it would improve performance by a lot in lower end computers.

Also, I noticed that the AUR version fails to build. No idea if it is a widespread issue or just my PC having a stroke.

**Comment by agam778** [comment]
Hmm, first of all, i don't think there is a way to block that in Electron. And secondly, it might break the functionality of the app too (I can be wrong too 🤷🏻 )

Also, talking about the AUR version:
There are two packages I published, first one is `ms-office-electron-bin` and `ms-office-electron-git`. Which one is giving you an error?
Also i tried installing both on my laptop and it installed successfully. Maybe tell what the error came while installing the package...

**Comment by RickRollMaster101** [comment]
No u wont close it

**Comment by RickRollMaster101** [comment]
get trolled, bot

**Comment by agam778** [comment]
Why don't u want to close it? The Creator of this issue hasn't responded yet so...This issue is stale?
Well it wasn't closed yet, it would've been closed in 7 days until Vanny responds...

**Comment by RickRollMaster101** [comment]
because troll

**Comment by agam778** [comment]
Please stop commenting useless things.

**Comment by RickRollMaster101** [comment]
no

**Comment by agam778** [comment]
Closing this issue as no response...

**Comment by RickRollMaster101** [comment]
> Closing this issue as no response...
> 
> Also, @RickRollMaster101 I did get the email of your comment and then you deleted it xD

why sus

**Comment by agam778** [comment]
Dude can you just stop these comments, it's Github Issues and not a chatting platform 😂😂
