### ISSUE TITLE
Opening word/excel is just a blank screen

### ISSUE THREAD

**Issue by FuzzyMistborn** [agam778/MS-Office-Electron#7]
The main screen loads up fine, but when I try to open a document I just get a blank white screen like this.

![image](https://user-images.githubusercontent.com/16689090/141127478-3ff304d4-1eff-49ad-be6e-2abe7585b435.png)

Have to close out of the app and reopen to get things working again.

**Comment by FuzzyMistborn** [comment]
As soon as I post this, it starts working, though there are still some times I get the above white screen.

**Comment by FuzzyMistborn** [comment]
Ummm....it's definitely not.  Or if it is it's taking over 5 minutes....which for a basic Word document doesn't seem right.

**Comment by agam778** [comment]
Hmm, did you try refreshing (Ctrl+R)?

Cause I have tried rn it doesnt have any problem tho 🤔

**Comment by agam778** [comment]
Hmm, even i tried rn but it works for me


________________________________

**Comment by FuzzyMistborn** [comment]
Sounds good, thanks!

**Comment by agam778** [comment]
Hey! Check if it works in the new version of app

**Comment by FuzzyMistborn** [comment]
Still get the white screen.  Clicking the "open log folder" in the menu does nothing.  Checking out `/~.config/ms-office-electron/logs/` shows just this:

[2021-11-11 09:42:29.769] [info]  You are connected to the internet!

**Comment by agam778** [comment]
Hmm, I use the app myself for my school work and other things, works perfectly without any problems for me + those too who tested my apps

I don't know what's the problem, open the browser, open https://office.com/?auth=1 and see if it works there.

**Comment by FuzzyMistborn** [comment]
Ahha, seems something on my network is blocking https://1drv.ms/.  Looks like a me issue then.  Thanks for the help!

**Comment by agam778** [comment]
No worries 😃

**Comment by FuzzyMistborn** [comment]
Just to close the loop in case anybody else runs into this, check your DNS block rules if you're running something like Adguard or PiHole.  For me, the [Big-List-of-Hacked-Malware-Web-Sites](https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts) was blocking 1drv.ms.
