### ISSUE TITLE
Enterprise Teams Client Fails to initialize

### ISSUE THREAD

**Issue by srlennon** [agam778/MS-Office-Electron#76]
When launching the teams app from the left pane a new windows launches but the Teams client fails to initialize reporting error "We're sorry—we've run into an issue. with the option to Try Again and if that fails try to sign out and back in again.

**Comment by agam778** [comment]
Are you using a personal or enterprise/student account?

Try setting the option "Open Websites in the Same Window" and try:

https://user-images.githubusercontent.com/68941022/194537970-6bbc23b4-ddf4-4005-8f33-640e173a5d71.mp4

**Comment by srlennon** [comment]
Thanks, this solved the problem when using enterprise account.

**Comment by agam778** [comment]
Cool! If everything's all right now, can the issue be closed?

**Comment by srlennon** [comment]
Confirmed.
