### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NightRaidGamer** [agam778/MS-Office-Electron#8]
hello, I would like to know if there is any trick to make it work offline even if I have to download some additional stuff...

**Comment by agam778** [comment]
Actually, it isn't possible as Microsoft Office (their website) cannot work offline 😢.

**Comment by NightRaidGamer** [comment]
> Actually, it isn't possible as Microsoft Office ([their website](https://office.com/?auth=1)) cannot work offline 😢

OK thank you for answering

**Comment by KaKi87** [comment]
Hello there,

I'm studying the possibility of making Office Online work offline, here are my notes :

The most important Office Online URL seems to be `https://onedrive.live.com/edit.aspx?resid=<ResourceId>`, which first `body` element is a `script` containing, among other things, the following data :
```json
{
    "WacApplication": "",
    "PageTitle": "",
    "WacBootstrapperUrl": "",
    "HostName": "OneDrive",
    "HostSessionId": "",
    "UserId": "",
    "OwnerId": "",
    "ApplicationUrl": "",
    "ResourceId": "",
    "ETag": "",
    "FileName": "",
    "FileGetUrl": "",
    "FileGetUrlExpiry": 0,
    "FileSize": 0,
    "ReadOnly": 0,
    "ViewOnly": 0,
    "AppEnabled": 1,
    "WopiSrc": "https://wopi.onedrive.com/wopi/files/<ResourceId>",
    "AccessToken": "",
    "AccessTokenExpiry": 0,
    "HostFlights": {}
}
```

Where :
- `ApplicationUrl`'s domain is `word-edit.officeapps.live.com` for docs, `powerpoint.officeapps.live.com` for slideshows, etc. ;
- `FileGetUrl` is the direct link to the file ;

Using [Electron's `interceptBufferProtocol` method](https://www.electronjs.org/docs/latest/api/protocol#protocolinterceptbufferprotocolscheme-handler), it is possible to make any request fired from any Electron-wrapped webapp reply whatever we want, including the abovementioned data, e.g. to make Office Online open offline resources.

I've made this work once with a much simpler MS App, that is the [Graph Explorer](https://git.kaki87.net/KaKi87/msgraphexplorer-desktop), but I think it could also be done here.

**Comment by KaKi87** [comment]
Additionally, the `ApplicationUrl` value is used to spawn an `iframe` at `onedrive.live.com`, which parameters look related to something called the [WOPI prototocol](https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/), allowing Microsoft & partners to embed Office Online into a parent app (in this case, OneDrive).

Instead of wrapping `onedrive.live.com`, maybe that value URL itself could be wrapped, leveraging said protocol.
