### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by JGMelon22** [agam778/MS-Office-Electron#80]
Just updated to 0.7.3, AUR port (based on .deb release) and AppImage are loading forever (tried on different devices). Tried open 0.7.2 on a backup laptop and worked like a charm at first try.

![x](https://user-images.githubusercontent.com/73988556/194618785-a928ba14-2901-4495-9a84-9dead763b869.png)

Node version Installed: v16.16.0
Electron version installed: v20.0.3
Inxi info: 
`System:
  Host: joao-ab350mgaming3 Kernel: 6.0.0-x64v2-xanmod1-1 arch: x86_64
    bits: 64 Desktop: Openbox v: 3.6.1 Distro: Archcraft
Machine:
  Type: Desktop System: Gigabyte product: AB350M-Gaming 3 v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: AB350M-Gaming 3-CF v: x.x
    serial: <superuser required> UEFI: American Megatrends v: F50d
    date: 07/02/2020
CPU:
  Info: 8-core model: AMD Ryzen 7 1700 bits: 64 type: MT MCP cache: L2: 4 MiB
  Speed (MHz): avg: 2928 min/max: 1550/3000 cores: 1: 3000 2: 3000 3: 3000
    4: 3000 5: 3000 6: 2697 7: 2609 8: 2797 9: 3000 10: 3000 11: 3000 12: 3000
    13: 2759 14: 3000 15: 3000 16: 3000
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.4 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa gpu: amdgpu resolution: 2560x1080~60Hz
  Message: Unable to show GL data. Required tool glxinfo missing.
Audio:
  Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
    driver: snd_hda_intel
  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel
  Sound Server-1: ALSA v: k6.0.0-x64v2-xanmod1-1 running: yes
  Sound Server-2: PulseAudio v: 16.1 running: yes
  Sound Server-3: PipeWire v: 0.3.58 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: e0:d5:5e:8f:34:ae
  IF-ID-1: docker0 state: up speed: 10000 Mbps duplex: unknown
    mac: 02:42:78:55:cd:f8
  IF-ID-2: vethf6cebf4 state: up speed: 10000 Mbps duplex: full
    mac: f2:6a:48:b3:32:9f
Drives:
  Local Storage: total: 1.13 TiB used: 167.33 GiB (14.5%)
  ID-1: /dev/sda vendor: Kingston model: SA400S37240G size: 223.57 GiB
  ID-2: /dev/sdb vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB
Partition:
  ID-1: / size: 214.42 GiB used: 27.05 GiB (12.6%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 952.1 MiB used: 288 KiB (0.0%) fs: vfat
    dev: /dev/sda1
  ID-3: /home size: 915.82 GiB used: 140.28 GiB (15.3%) fs: ext4
    dev: /dev/sdb1
Swap:
  Alert: No swap data was found.
Sensors:
  System Temperatures: cpu: 30.9 C mobo: N/A gpu: amdgpu temp: 47.0 C
  Fan Speeds (RPM): N/A gpu: amdgpu fan: 770
Info:
  Processes: 386 Uptime: 6h 14m Memory: 15.58 GiB used: 8.15 GiB (52.3%)
  Shell: Zsh inxi: 3.3.21`

**Comment by agam778** [comment]
Weird, it's working fine for me.

Can you send the logs? (Application -> Open Logs Folder -> Send the `main.log`)
and also try once again

![image](https://user-images.githubusercontent.com/68941022/194625155-47782995-bd05-4ecd-b956-26d6301161c2.png)

**Comment by JGMelon22** [comment]
Can't even achieve this window, just the loading screen :/
Will try to find where log folders are stored on AUR version and get back tou you, ty :)

**Comment by agam778** [comment]
![Screenshot_20221008-000956_Samsung_Internet.png](https://user-images.githubusercontent.com/68941022/194627085-1a738f1c-0934-41a9-a019-e552f1ba8618.png)

Might be `~/.config/ms-office-electron/logs/main.log` or `~/.config/MS-Office-Electron/logs/main.log`

**Comment by JGMelon22** [comment]
After a while, closed using xkill as it was not loading
`
[2022-10-07 15:45:59.060] [warn]  APPIMAGE env is not defined, current application is not an AppImage
[2022-10-07 15:45:59.203] [info]  You are connected to the internet!
[2022-10-07 15:46:16.786] [error] (node:106741) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'write')
    at IPCTransport.send (/opt/MS-Office-Electron/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /opt/MS-Office-Electron/resources/app.asar/node_modules/discord-rpc/src/client.js:159:22
    at new Promise (<anonymous>)
    at RPCClient.request (/opt/MS-Office-Electron/resources/app.asar/node_modules/discord-rpc/src/client.js:157:12)
    at RPCClient.clearActivity (/opt/MS-Office-Electron/resources/app.asar/node_modules/discord-rpc/src/client.js:540:17)
    at App.<anonymous> (/opt/MS-Office-Electron/resources/app.asar/main.js:563:7)
    at App.emit (node:events:539:35)
(Use `ms-office-electron --trace-warnings ...` to show where the warning was created)
[2022-10-07 15:46:16.788] [error] (node:106741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`

**Comment by JGMelon22** [comment]
I tan the AppImage from 0.7.2 and all of the sudden started working... Any way, thanks a lot  agam :D

**Comment by JGMelon22** [comment]
My mistake, not worked at all. After ran 0.7.2, the newer version does open till login screen, whoever I do need to force reload. After closing and opening it again, the same behavior happens.

**Comment by JGMelon22** [comment]
Apparently fix: 
- Uninstall 0.7.3
- Browse to `~/.config` and delete the directory `ms-office-electron`
- Install the package again
@agam778 closing the issue. TY, mate

**Comment by agam778** [comment]
Wait a second, when you opened the app, was there a window showing that there is an error connecting to discord rpc?

**Comment by JGMelon22** [comment]
Nope. The only window displayed was the loading one
![image](https://user-images.githubusercontent.com/73988556/194691776-79768cc6-c11e-49f4-b3ce-845ad8177b96.png)
Neither did I see an output mentioning it on terminal

**Comment by agam778** [comment]
Can you alt+tab and check because it sometimes gets hidden behind?

**Comment by JGMelon22** [comment]
Unfortunately can not reproduce any more, at least I think I can not. After doing the "going macgyver", this problem was fixed at all + it is 3 am where do I live. Will try to reproduce it later on a spare machine, Ok?

**Comment by agam778** [comment]
Yep, no problem, and thanks!

**Comment by JGMelon22** [comment]
> Yep, no problem, and thanks!

So, just tested the AppImage version (due to convince as the laptop runs Solus) and the Discord RPC message shows on terminal at first boot, whoever I am able to login and use normally at first launch. After setup to disable the Discord RPC (as I do not have it installed on that machine), it simply stuck at the loading screen. My desktop and main laptop do have discord installed by the way

**Comment by agam778** [comment]
Well, I disabled and enabled discord rpc both and it works for me

**Comment by agam778** [comment]
This is what happens to me, 
![image](https://user-images.githubusercontent.com/68941022/194718755-e819a379-2967-489b-a58e-591778dd249b.png)
and then it normally opens the app

**Comment by JGMelon22** [comment]
In my case, at least on Solus machine, was just prompting a message if I ran it trough terminal, and still stuck on loading window. Any way, my guesses are I was out of luck instead of a bug 😅
