### ISSUE TITLE
Some Improvment 

### ISSUE THREAD

**Issue by AnisTaluqdar** [agam778/MS-Office-Electron#9]
Thanks for your project. 
I wish to have,
1. Back button
2. Home button
3. Open document in main tab instead of new window
4. Option for hide menu bar

**Comment by agam778** [comment]
Hi 👋🏻  Thanks for opening this issue.

I have just implemented what you said. And the Back and Home button is under an App Menu called "Navigation", because I cannot add a url bar type thing in electron.

Here is a preview: [GIF Link](https://cdn.upload.systems/uploads/72NjRLBs.gif)

Please tell if it's fine so I can release the new build :)

**Comment by AnisTaluqdar** [comment]
@agam778 Thank you so much. for quick fix. 

It's very fine. the opening theme can be more standard. I have problem with appimage icon. the appimage icon is not working.

**Comment by agam778** [comment]
> the opening theme can be more standard
You mean the thing it shows while loading at the first launch right?

> the appimage icon is not working.
I'll have to test it. Give me some time

**Comment by AnisTaluqdar** [comment]
> > the appimage icon is not working.
Yes

**Comment by agam778** [comment]
Oh yes, the AppImage icon is broken for me. I'll try to fix

**Comment by agam778** [comment]
So I tried to fix, but can't test atm as I just have Gentoo installed right now and it doesn't have some stuff.

Well, you can try installing `appimaged` daemon as mentioned here - https://github.com/electron-userland/electron-builder/issues/748

I'll release the new build soon

**Comment by agam778** [comment]
Released - https://github.com/agam778/MS-Office-Electron/releases/tag/v0.5.0
Please check if everything's correct :)

**Comment by AnisTaluqdar** [comment]
Hide menu bar not working. it's just hide whenever you press ALT otherwise by default it always show the menu bar

**Comment by agam778** [comment]
> Hide menu bar not working. it's just hide whenever you press ALT otherwise by default it always show the menu bar

You'll have to just click alt once to hide it, then it will be hidden anywhere. Electron's behaviour

**Comment by AnisTaluqdar** [comment]
but if you re open the app. it shows menu bar and you need to hide by pressing ALT

**Comment by agam778** [comment]
Hides for me when I click anywhere in the window 🤷🏻‍♂️ 

![MS-Office-Electron_zSfy2JtiMY](https://user-images.githubusercontent.com/68941022/155948557-381ac235-ffb2-4511-92b6-f66c0f283021.gif)

**Comment by AnisTaluqdar** [comment]
hmm, it's hide automatically after when i hide and un hide window after reopening app.

**Comment by agam778** [comment]
> hmm, it's hide automatically after when i hide and un hide window after reopening app.

Yep, probably the menu bar is focused when the app is launched.

**Comment by AnisTaluqdar** [comment]
and command ALT already used for Excel menu bar. when I open excel and press the ALT it select the excel menu instead of top app bar.

**Comment by agam778** [comment]
Please turn off Override Shortcuts

![image](https://user-images.githubusercontent.com/68941022/155949590-81b88a84-7641-47c8-a506-63201b518fc6.png)

![image](https://user-images.githubusercontent.com/68941022/155949515-952abc28-3650-4b2b-90a5-38f141f9b53d.png)
